"""Initial migration with source and overall summaries

Revision ID: 001
Revises:
Create Date: 2026-02-09 22:01:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "overall_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pdf_set_hash", sa.String(), nullable=False),
        sa.Column("pdf_file_names", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pdf_set_hash"),
    )
    op.create_index(
        op.f("ix_overall_summaries_pdf_set_hash"),
        "overall_summaries",
        ["pdf_set_hash"],
        unique=False,
    )
    op.create_table(
        "source_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name"),
    )
    op.create_index(
        op.f("ix_source_summaries_source_name"),
        "source_summaries",
        ["source_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_source_summaries_source_name"), table_name="source_summaries"
    )
    op.drop_table("source_summaries")
    op.drop_index(
        op.f("ix_overall_summaries_pdf_set_hash"), table_name="overall_summaries"
    )
    op.drop_table("overall_summaries")
    # ### end Alembic commands ###
