"""Update pdfs table for notebook uniqueness

Revision ID: f2ba32b9cace
Revises: c575937cf112
Create Date: 2026-02-09 18:34:55.194570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ba32b9cace'
down_revision: Union[str, Sequence[str], None] = 'c575937cf112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdfs_file_name'), table_name='pdfs')
    op.create_index(op.f('ix_pdfs_file_name'), 'pdfs', ['file_name'], unique=False)
    op.create_unique_constraint('uix_pdf_filename_notebook', 'pdfs', ['file_name', 'notebook_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_pdf_filename_notebook', 'pdfs', type_='unique')
    op.drop_index(op.f('ix_pdfs_file_name'), table_name='pdfs')
    op.create_index(op.f('ix_pdfs_file_name'), 'pdfs', ['file_name'], unique=True)
    # ### end Alembic commands ###
