"""Add notebooks and pdfs tables

Revision ID: c575937cf112
Revises: 001
Create Date: 2026-02-09 18:19:30.715010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c575937cf112'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_notebook_id'), 'notebooks', ['notebook_id'], unique=True)
    op.create_table('pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.String(), server_default='uploaded', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdfs_file_name'), 'pdfs', ['file_name'], unique=True)
    op.drop_constraint(op.f('overall_summaries_pdf_set_hash_key'), 'overall_summaries', type_='unique')
    op.drop_index(op.f('ix_overall_summaries_pdf_set_hash'), table_name='overall_summaries')
    op.create_index(op.f('ix_overall_summaries_pdf_set_hash'), 'overall_summaries', ['pdf_set_hash'], unique=True)
    op.drop_constraint(op.f('source_summaries_source_name_key'), 'source_summaries', type_='unique')
    op.drop_index(op.f('ix_source_summaries_source_name'), table_name='source_summaries')
    op.create_index(op.f('ix_source_summaries_source_name'), 'source_summaries', ['source_name'], unique=True)
    op.create_index(op.f('ix_source_summaries_id'), 'source_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_summaries_id'), table_name='source_summaries')
    op.drop_index(op.f('ix_source_summaries_source_name'), table_name='source_summaries')
    op.create_index(op.f('ix_source_summaries_source_name'), 'source_summaries', ['source_name'], unique=False)
    op.create_unique_constraint(op.f('source_summaries_source_name_key'), 'source_summaries', ['source_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_overall_summaries_pdf_set_hash'), table_name='overall_summaries')
    op.create_index(op.f('ix_overall_summaries_pdf_set_hash'), 'overall_summaries', ['pdf_set_hash'], unique=False)
    op.create_unique_constraint(op.f('overall_summaries_pdf_set_hash_key'), 'overall_summaries', ['pdf_set_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pdfs_file_name'), table_name='pdfs')
    op.drop_table('pdfs')
    op.drop_index(op.f('ix_notebooks_notebook_id'), table_name='notebooks')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
